<h3>Users</h3>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Email</th>
        <!--<th>Ação</th>-->
    </tr>

    <?php foreach ($this->data as $entity): ?>
        <tr>
            <td> <?php echo $entity->getId(); ?></td>
            <td> <?php echo $entity->getNome(); ?></td>
            <td> <?php echo $entity->getemail(); ?></td>
            <td> </td>
        </tr>

    <?php endforeach; ?>
</table>