<h3>Users</h3>

<p>
    <a href="<?php echo $this->url('sonuser-admin',array('action'=>'new')); ?>">
        Novo
    </a> 
</p>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Ação</th>
    </tr>

    <?php foreach ($this->data as $entity): ?>
        <tr>
            <td> <?php echo $entity->getId(); ?></td>
            <td> <?php echo $entity->getNome(); ?></td>
            <td> <?php echo $entity->getEmail(); ?></td>
            <td>
                <a href="<?php echo $this->url('sonuser-admin',array('controller'=>'users','action'=>'edit', 'id'=>$entity->getId())); ?>">
                    Editar
                </a>
                                <a href="<?php echo $this->url('sonuser-admin',array('controller'=>'users','action'=>'delete', 'id'=>$entity->getId())); ?>">
                    Excluir
                </a>    
            </td>
        </tr>

    <?php endforeach; ?>
</table>